create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null unique,
  ip text,
  user_agent text
);

alter table public.waitlist enable row level security;

grant insert, select on table public.waitlist to service_role;
grant usage, select on sequence public.waitlist_id_seq to service_role;
